### ISSUE TITLE
What could be the reason for different output for the same query on 2 different computers?

### ISSUE THREAD

**Issue by amks1** [gsimardnet/PowerQueryNet#22]
I am running a query within an excel file. I run the query on one computer, and it gives me a wrong output. 
I copy the exact same file to another computer, run it, and it gives me the correct output. 

I installed PowerQueryNet on both computers from the same installation files. 

I'm stumped, what could be the reason for this?

**Comment by gsimardnet** [comment]
I never saw that kind of issue. Does your query have any other dependency or is it just reading an Excel file ?
Since both computers have Excel, did you try to run the same Power Query using the "Get Data" feature from Excel ? What do they ouput ?

**Comment by amks1** [comment]
The query has the following steps:
![image](https://user-images.githubusercontent.com/68153785/111350599-b59dc280-869b-11eb-97e2-378efcf09ad5.png)

The source is an excel file whereas the merged table is from a web API. 

Yes I ran the queries within excel and it returns the correct results in both computers loaded into the excel sheet. But when Power Query Net runs, it outputs the wrong result (I'm using `-o csv`)  on one computer.

**Comment by gsimardnet** [comment]
Then it could be related to issue #17.

**Comment by amks1** [comment]
I don't understand how? 
There's no commas in these files.

**Comment by gsimardnet** [comment]
I think I misunderstood. Now I see that you use "-o csv" in both computers. So I guess the problem is elsewhere but to be sure, did you try a different ouput ?

Otherwise, I would look into the Regional Settings parameters and compare both computers.
Go in "Control Panel\All Control Panel Items\Region" do you have the same format ? 
Then click the Administrative tab and "Change system locale..." button. Be sure that they have the same settings there too. 
You can also type chcp in the command prompt to see your current active code page.

**Comment by amks1** [comment]
@gsimardnet 
Problem is now solved. Everything was the same in both computers except the "Regional Format". 
![image](https://user-images.githubusercontent.com/68153785/111528944-09cba400-877b-11eb-8297-92251af763cc.png)

In the computer with the correct output it was "English (World)" whereas in the offending one it was "English (United States)". After changing it to "English (World)" the output is now as expected. 

Although I don't have a clue how that could lead to such a huge disparity (especially when Excel displayed the correct output on both), I'm glad it's now fixed. Thanks for the help!
